export const DATA_UPDATED_LABEL = 'Demo dataset reviewed: 2026-05-13';

export const markets = [
  {
    id: 'USA',
    label: 'United States',
    shortLabel: 'USA',
    currency: 'USD',
    exchangeHint: 'NASDAQ / NYSE',
  },
  {
    id: 'SG',
    label: 'Singapore',
    shortLabel: 'SG',
    currency: 'SGD',
    exchangeHint: 'SGX',
  },
  {
    id: 'MY',
    label: 'Malaysia',
    shortLabel: 'MY',
    currency: 'MYR',
    exchangeHint: 'Bursa Malaysia',
  },
];

export const stocks = [
  { market: 'USA', ticker: 'AAPL', company: 'Apple Inc.', sector: 'Technology', currency: 'USD', trendScore: 96, demoPrice: 294.8, demoChangePercent: 0.72, note: 'Mega-cap device and services leader.' },
  { market: 'USA', ticker: 'MSFT', company: 'Microsoft Corporation', sector: 'Technology', currency: 'USD', trendScore: 95, demoPrice: 407.77, demoChangePercent: -1.18, note: 'Cloud, productivity, and AI platform exposure.' },
  { market: 'USA', ticker: 'NVDA', company: 'NVIDIA Corporation', sector: 'Semiconductors', currency: 'USD', trendScore: 98, demoPrice: 118.34, demoChangePercent: 1.84, note: 'AI accelerator and data-center demand theme.' },
  { market: 'USA', ticker: 'AMZN', company: 'Amazon.com Inc.', sector: 'Consumer Discretionary', currency: 'USD', trendScore: 92, demoPrice: 183.11, demoChangePercent: 0.47, note: 'E-commerce scale with cloud optionality.' },
  { market: 'USA', ticker: 'GOOGL', company: 'Alphabet Inc.', sector: 'Communication Services', currency: 'USD', trendScore: 91, demoPrice: 171.23, demoChangePercent: 0.38, note: 'Search, ads, cloud, and AI products.' },
  { market: 'USA', ticker: 'META', company: 'Meta Platforms Inc.', sector: 'Communication Services', currency: 'USD', trendScore: 90, demoPrice: 498.42, demoChangePercent: 1.12, note: 'Social platforms and AI ad tooling.' },
  { market: 'USA', ticker: 'TSLA', company: 'Tesla Inc.', sector: 'Consumer Discretionary', currency: 'USD', trendScore: 88, demoPrice: 177.8, demoChangePercent: -0.93, note: 'EV, battery, and autonomy sentiment proxy.' },
  { market: 'USA', ticker: 'AVGO', company: 'Broadcom Inc.', sector: 'Semiconductors', currency: 'USD', trendScore: 89, demoPrice: 142.74, demoChangePercent: 0.83, note: 'Chips and infrastructure software exposure.' },
  { market: 'USA', ticker: 'JPM', company: 'JPMorgan Chase & Co.', sector: 'Financials', currency: 'USD', trendScore: 84, demoPrice: 221.52, demoChangePercent: 0.26, note: 'Large bank and capital markets bellwether.' },
  { market: 'USA', ticker: 'LLY', company: 'Eli Lilly and Company', sector: 'Healthcare', currency: 'USD', trendScore: 87, demoPrice: 762.3, demoChangePercent: 0.61, note: 'Healthcare growth and obesity drug theme.' },
  { market: 'USA', ticker: 'V', company: 'Visa Inc.', sector: 'Financials', currency: 'USD', trendScore: 82, demoPrice: 284.18, demoChangePercent: -0.14, note: 'Payments network quality compounder.' },
  { market: 'USA', ticker: 'AMD', company: 'Advanced Micro Devices Inc.', sector: 'Semiconductors', currency: 'USD', trendScore: 86, demoPrice: 151.67, demoChangePercent: 1.05, note: 'CPU, GPU, and AI chip challenger.' },
  { market: 'USA', ticker: 'NFLX', company: 'Netflix Inc.', sector: 'Communication Services', currency: 'USD', trendScore: 81, demoPrice: 642.9, demoChangePercent: 0.34, note: 'Streaming scale and ad tier momentum.' },
  { market: 'USA', ticker: 'COST', company: 'Costco Wholesale Corporation', sector: 'Consumer Staples', currency: 'USD', trendScore: 80, demoPrice: 818.45, demoChangePercent: -0.21, note: 'Membership retail defensive growth.' },
  { market: 'USA', ticker: 'HD', company: 'The Home Depot Inc.', sector: 'Consumer Discretionary', currency: 'USD', trendScore: 76, demoPrice: 336.28, demoChangePercent: 0.18, note: 'Housing repair and improvement exposure.' },
  { market: 'USA', ticker: 'ORCL', company: 'Oracle Corporation', sector: 'Technology', currency: 'USD', trendScore: 83, demoPrice: 124.91, demoChangePercent: 0.75, note: 'Enterprise software and cloud infrastructure.' },
  { market: 'USA', ticker: 'BAC', company: 'Bank of America Corporation', sector: 'Financials', currency: 'USD', trendScore: 74, demoPrice: 38.64, demoChangePercent: -0.32, note: 'Large-bank rate and credit sensitivity.' },
  { market: 'USA', ticker: 'WMT', company: 'Walmart Inc.', sector: 'Consumer Staples', currency: 'USD', trendScore: 79, demoPrice: 68.55, demoChangePercent: 0.24, note: 'Large-scale retail and grocery exposure.' },
  { market: 'USA', ticker: 'PLTR', company: 'Palantir Technologies Inc.', sector: 'Technology', currency: 'USD', trendScore: 85, demoPrice: 22.74, demoChangePercent: 2.08, note: 'Data analytics and AI platform theme.' },
  { market: 'USA', ticker: 'CRM', company: 'Salesforce Inc.', sector: 'Technology', currency: 'USD', trendScore: 78, demoPrice: 244.19, demoChangePercent: -0.48, note: 'Enterprise CRM and workflow platform.' },

  { market: 'SG', ticker: 'D05', company: 'DBS Group Holdings Ltd', sector: 'Financials', currency: 'SGD', trendScore: 95, demoPrice: 59.9, demoChangePercent: 1.35, note: 'Singapore bank and dividend income favorite.' },
  { market: 'SG', ticker: 'O39', company: 'OCBC Ltd', sector: 'Financials', currency: 'SGD', trendScore: 92, demoPrice: 22.89, demoChangePercent: 2.51, note: 'Regional bank with wealth exposure.' },
  { market: 'SG', ticker: 'U11', company: 'United Overseas Bank Ltd', sector: 'Financials', currency: 'SGD', trendScore: 91, demoPrice: 39.72, demoChangePercent: 1.04, note: 'ASEAN banking franchise.' },
  { market: 'SG', ticker: 'Z74', company: 'Singapore Telecommunications Ltd', sector: 'Communication Services', currency: 'SGD', trendScore: 88, demoPrice: 4.82, demoChangePercent: 2.12, note: 'Telecom and regional digital infrastructure.' },
  { market: 'SG', ticker: 'C38U', company: 'CapitaLand Integrated Commercial Trust', sector: 'Real Estate', currency: 'SGD', trendScore: 84, demoPrice: 2.18, demoChangePercent: 0.46, note: 'Retail and office REIT exposure.' },
  { market: 'SG', ticker: 'C09', company: 'City Developments Ltd', sector: 'Real Estate', currency: 'SGD', trendScore: 72, demoPrice: 5.32, demoChangePercent: -0.37, note: 'Property developer and hotel exposure.' },
  { market: 'SG', ticker: 'S68', company: 'Singapore Exchange Ltd', sector: 'Financials', currency: 'SGD', trendScore: 86, demoPrice: 11.41, demoChangePercent: 0.62, note: 'Market infrastructure and exchange income.' },
  { market: 'SG', ticker: 'BN4', company: 'Keppel Ltd', sector: 'Industrials', currency: 'SGD', trendScore: 82, demoPrice: 7.05, demoChangePercent: 0.28, note: 'Infrastructure, energy, and asset management.' },
  { market: 'SG', ticker: 'F34', company: 'Wilmar International Ltd', sector: 'Consumer Staples', currency: 'SGD', trendScore: 75, demoPrice: 3.18, demoChangePercent: -0.31, note: 'Agribusiness and food supply chain.' },
  { market: 'SG', ticker: 'G13', company: 'Genting Singapore Ltd', sector: 'Consumer Discretionary', currency: 'SGD', trendScore: 74, demoPrice: 0.89, demoChangePercent: 0.56, note: 'Integrated resort and tourism proxy.' },
  { market: 'SG', ticker: 'C6L', company: 'Singapore Airlines Ltd', sector: 'Industrials', currency: 'SGD', trendScore: 83, demoPrice: 6.47, demoChangePercent: 0.78, note: 'Aviation recovery and premium travel theme.' },
  { market: 'SG', ticker: 'A17U', company: 'CapitaLand Ascendas REIT', sector: 'Real Estate', currency: 'SGD', trendScore: 80, demoPrice: 2.78, demoChangePercent: 0.36, note: 'Industrial and business park REIT.' },
  { market: 'SG', ticker: 'ME8U', company: 'Mapletree Industrial Trust', sector: 'Real Estate', currency: 'SGD', trendScore: 79, demoPrice: 2.29, demoChangePercent: 0.44, note: 'Data center and industrial REIT mix.' },
  { market: 'SG', ticker: 'M44U', company: 'Mapletree Logistics Trust', sector: 'Real Estate', currency: 'SGD', trendScore: 77, demoPrice: 1.42, demoChangePercent: -0.7, note: 'Regional logistics REIT exposure.' },
  { market: 'SG', ticker: 'N2IU', company: 'Mapletree Pan Asia Commercial Trust', sector: 'Real Estate', currency: 'SGD', trendScore: 76, demoPrice: 1.31, demoChangePercent: 0.0, note: 'Commercial and retail property income.' },
  { market: 'SG', ticker: 'T82U', company: 'Suntec REIT', sector: 'Real Estate', currency: 'SGD', trendScore: 70, demoPrice: 1.19, demoChangePercent: -0.83, note: 'Office and retail REIT.' },
  { market: 'SG', ticker: 'AJBU', company: 'Keppel DC REIT', sector: 'Real Estate', currency: 'SGD', trendScore: 81, demoPrice: 1.98, demoChangePercent: 0.51, note: 'Data center REIT theme.' },
  { market: 'SG', ticker: 'BS6', company: 'Yangzijiang Shipbuilding Holdings Ltd', sector: 'Industrials', currency: 'SGD', trendScore: 85, demoPrice: 2.45, demoChangePercent: 1.24, note: 'Shipbuilding orderbook momentum.' },
  { market: 'SG', ticker: 'Y92', company: 'Thai Beverage PCL', sector: 'Consumer Staples', currency: 'SGD', trendScore: 71, demoPrice: 0.52, demoChangePercent: -0.95, note: 'Beverage and ASEAN consumption exposure.' },
  { market: 'SG', ticker: 'S63', company: 'Singapore Technologies Engineering Ltd', sector: 'Industrials', currency: 'SGD', trendScore: 87, demoPrice: 4.72, demoChangePercent: 0.64, note: 'Defense, aerospace, and smart city exposure.' },

  { market: 'MY', ticker: 'MAYBANK', company: 'Malayan Banking Bhd.', sector: 'Financials', currency: 'MYR', trendScore: 94, demoPrice: 11.18, demoChangePercent: -0.53, note: 'Large Malaysian bank and dividend proxy.' },
  { market: 'MY', ticker: 'CIMB', company: 'CIMB Group Holdings Bhd', sector: 'Financials', currency: 'MYR', trendScore: 90, demoPrice: 7.92, demoChangePercent: 0.25, note: 'ASEAN banking and loan growth exposure.' },
  { market: 'MY', ticker: 'PBBANK', company: 'Public Bank Bhd', sector: 'Financials', currency: 'MYR', trendScore: 86, demoPrice: 4.58, demoChangePercent: 0.22, note: 'Retail banking quality franchise.' },
  { market: 'MY', ticker: 'TENAGA', company: 'Tenaga Nasional Bhd', sector: 'Utilities', currency: 'MYR', trendScore: 88, demoPrice: 14.26, demoChangePercent: 0.71, note: 'National utility and grid investment theme.' },
  { market: 'MY', ticker: 'IHH', company: 'IHH Healthcare Bhd', sector: 'Healthcare', currency: 'MYR', trendScore: 84, demoPrice: 6.41, demoChangePercent: 0.47, note: 'Regional private healthcare operator.' },
  { market: 'MY', ticker: 'PETGAS', company: 'Petronas Gas Bhd', sector: 'Energy', currency: 'MYR', trendScore: 78, demoPrice: 17.72, demoChangePercent: -0.17, note: 'Gas infrastructure and stable cash flow.' },
  { market: 'MY', ticker: 'PCHEM', company: 'Petronas Chemicals Group Bhd', sector: 'Materials', currency: 'MYR', trendScore: 73, demoPrice: 5.68, demoChangePercent: -0.7, note: 'Petrochemical cycle exposure.' },
  { market: 'MY', ticker: 'AXIATA', company: 'Axiata Group Bhd', sector: 'Communication Services', currency: 'MYR', trendScore: 70, demoPrice: 2.31, demoChangePercent: 0.43, note: 'Regional telecom portfolio.' },
  { market: 'MY', ticker: 'MAXIS', company: 'Maxis Bhd', sector: 'Communication Services', currency: 'MYR', trendScore: 72, demoPrice: 3.64, demoChangePercent: -0.27, note: 'Mobile and broadband income exposure.' },
  { market: 'MY', ticker: 'CDB', company: 'CelcomDigi Bhd', sector: 'Communication Services', currency: 'MYR', trendScore: 75, demoPrice: 4.12, demoChangePercent: 0.49, note: 'Telecom merger synergy theme.' },
  { market: 'MY', ticker: 'SIME', company: 'Sime Darby Bhd', sector: 'Industrials', currency: 'MYR', trendScore: 74, demoPrice: 2.58, demoChangePercent: 0.39, note: 'Industrial distribution and autos.' },
  { market: 'MY', ticker: 'MISC', company: 'MISC Bhd', sector: 'Energy', currency: 'MYR', trendScore: 76, demoPrice: 7.43, demoChangePercent: 0.13, note: 'LNG shipping and offshore exposure.' },
  { market: 'MY', ticker: 'KLK', company: 'Kuala Lumpur Kepong Bhd', sector: 'Consumer Staples', currency: 'MYR', trendScore: 71, demoPrice: 21.44, demoChangePercent: -0.28, note: 'Plantation and oleochemical exposure.' },
  { market: 'MY', ticker: 'IOICORP', company: 'IOI Corporation Bhd', sector: 'Consumer Staples', currency: 'MYR', trendScore: 69, demoPrice: 4.02, demoChangePercent: 0.0, note: 'Plantation and palm oil value chain.' },
  { market: 'MY', ticker: 'GENTING', company: 'Genting Bhd', sector: 'Consumer Discretionary', currency: 'MYR', trendScore: 68, demoPrice: 4.71, demoChangePercent: 0.64, note: 'Gaming, leisure, and plantation holding company.' },
  { market: 'MY', ticker: 'GENM', company: 'Genting Malaysia Bhd', sector: 'Consumer Discretionary', currency: 'MYR', trendScore: 67, demoPrice: 2.74, demoChangePercent: -0.36, note: 'Resort and tourism recovery proxy.' },
  { market: 'MY', ticker: 'RHBBANK', company: 'RHB Bank Bhd', sector: 'Financials', currency: 'MYR', trendScore: 80, demoPrice: 6.18, demoChangePercent: 0.81, note: 'Domestic banking exposure.' },
  { market: 'MY', ticker: 'HLBANK', company: 'Hong Leong Bank Bhd', sector: 'Financials', currency: 'MYR', trendScore: 82, demoPrice: 20.44, demoChangePercent: 0.2, note: 'High-quality banking franchise.' },
  { market: 'MY', ticker: 'TM', company: 'Telekom Malaysia Bhd', sector: 'Communication Services', currency: 'MYR', trendScore: 79, demoPrice: 6.62, demoChangePercent: 0.61, note: 'Fixed broadband and enterprise connectivity.' },
  { market: 'MY', ticker: 'INARI', company: 'Inari Amertron Bhd', sector: 'Technology', currency: 'MYR', trendScore: 83, demoPrice: 3.18, demoChangePercent: 1.27, note: 'Semiconductor assembly and electronics theme.' },
];

const usaExchangeByTicker = {
  AAPL: 'NASDAQ',
  MSFT: 'NASDAQ',
  NVDA: 'NASDAQ',
  AMZN: 'NASDAQ',
  GOOGL: 'NASDAQ',
  META: 'NASDAQ',
  TSLA: 'NASDAQ',
  AVGO: 'NASDAQ',
  JPM: 'NYSE',
  LLY: 'NYSE',
  V: 'NYSE',
  AMD: 'NASDAQ',
  NFLX: 'NASDAQ',
  COST: 'NASDAQ',
  HD: 'NYSE',
  ORCL: 'NYSE',
  BAC: 'NYSE',
  WMT: 'NYSE',
  PLTR: 'NASDAQ',
  CRM: 'NYSE',
};

export function getTradingViewSymbol(stock) {
  if (stock.market === 'USA') return `${usaExchangeByTicker[stock.ticker] || 'NASDAQ'}:${stock.ticker}`;
  if (stock.market === 'SG') return `SGX:${stock.ticker}`;
  if (stock.market === 'MY') return `MYX:${stock.ticker}`;
  return stock.ticker;
}
